language: php

php:
  - 7.3

before_script:
  - composer self-update
  - composer install --no-interaction
  - sudo apt-get install nodejs
  - npm install

script:
  - npm run production

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: source
  keep_history: true
  local_dir: build_production
  target_branch: master
  
